test-nix:
  script:
    - rm -rf tests/tmp
    - mkdir -p tests/tmp
    - php tools/phpunit.phar --verbose tests/ProcessTest
    - php tools/phpunit.phar --verbose tests/ControlTest
  tags:
    - nodejs
    - nix
	- php
test-win:
  script:
	- php tools/phpunit.phar --verbose tests/ProcessTest
	- php tools/phpunit.phar --verbose tests/ControlTest
  tags:
    - windows
    - nodejs
    - php
doc:
  script:
    - php tools/phpDocumentor.phar -p -d src/ -t doc/ --template="clean"
