before_script:
  - rm -rf tests/tmp tools doc
  - mkdir tools

test:
  script:
    - mkdir tests/tmp
    - wget -O tools/phpunit.phar https://phar.phpunit.de/phpunit.phar
    - php tools/phpunit.phar tests/NodeJSControlTest
doc:
  script:
    - mkdir doc
    - wget -O tools/phpDocumentor.phar http://phpdoc.org/phpDocumentor.phar
    - php tools/phpDocumentor.phar -d src/ -t doc/
